version: "2"

services:
### console
    console:
        build:
            context: ./images/console
            args:
                # console 容器 www-data用户密码
                - USERPASS=root
                - GIT_NAME=git_name
                - GIT_EMAIL=git_email
                - INSTALL_YARN=false
        volumes_from:
            - php-fpm
            - nginx
            - mysql
            - redis
        volumes:
            - ./ssh:/home/www-data/.ssh
        tty: true

### php-fpm
    php-fpm:
        build: ./images/php-fpm
        volumes:
            - ../:/var/www/
        extra_hosts:
            - "aw.me:10.0.75.1"

### nginx
    nginx:
        image: nginx:1.11.10-alpine
        ports:
            - "80:80"
        volumes_from:
            - php-fpm
        volumes:
            - ./logs/nginx/:/var/log/nginx/
            - ./images/nginx/sites:/etc/nginx/conf.d/
            - ./images/nginx/nginx.conf:/etc/nginx/nginx.conf

### mysql
    mysql:
        image: mysql:8.0.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "test"
            MYSQL_USER: "test"
            MYSQL_PASSWORD: "test"
        volumes:
            - ./data/mysql:/var/lib/mysql

### redis
    redis:
        image: redis:3.0.7
        ports:
            - "6379:6379"
        volumes:
            - ./data/redis:/data
